### ISSUE TITLE
Positive label for F1 measure is not configured correctly

### ISSUE THREAD

**Issue by ywatanabex** [mhagiwara/realworldnlp#1]
I reviewed the code: examples/sentiment/sst_classifier.py, and found a bug.

        self.f1_measure = F1Measure(4)

I think this code is intended to measure precision/recall/f1 for the label '4' which is the most positive sentiment. However, the integer 4 here is considered as index in the array representation. It must be converted using label mapping stored in vocab.

**Comment by mhagiwara** [comment]
Thanks for pointing this out @ywatanabex. Fixed in the latest commit.
