### ISSUE TITLE
Using GPU

### ISSUE THREAD

**Issue by perdix** [mhagiwara/realworldnlp#2]
Great Tutorial!
It would be very cool, if you can describe how to use the GPU to run it faster.

**Comment by 0xpantera** [comment]
It's fairly easy to move the model to the GPU. Try the following:
Get the device you have:

`device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")`

Instantiate your model:

`model = LstmClassifier(word_embeddings, encoder, vocab)`

Move the model to the GPU:

`model = model.to(device)`

Additionally the Allennlp `Trainer` has an option to pass the `cuda_device`. So you would have something like the following:
```
trainer = Trainer(model=model,
                  optimizer=optimizer,
                  iterator=iterator,
                  train_dataset=train_dataset,
                  validation_dataset=dev_dataset,
                  patience=10,
                  num_epochs=20,
                  cuda_device=device.index)
```
That's it!

**Comment by perdix** [comment]
Thanks a lot! :+1:
